services:
  # MongoDB database replica cluster
  mongo-dev:
    image: mongo:4.4.18
    container_name: mongo-dev
    command: mongod --replSet rs0 --bind_ip localhost,mongo-dev
    ports:
      - "27017:27017"
    volumes:
      - mongo-dev:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/mongo-init.js
    networks:
      - skillforge-net
    restart: always

  # Piston API instance
  piston-api:
    image: ghcr.io/engineer-man/piston@sha256:6500f2af69ce18fe16ca9a0ba7b0ea895366fc0efa46860c03d1d3c8a6cd270d
    container_name: piston-api
    ports:
      - "2000:2000"
    privileged: true
    volumes:
      - ../data/piston/packages:/piston/packages
    tmpfs:
      - /tmp:exec
    networks:
      - skillforge-net
    restart: always

volumes:
  mongo-dev:
    driver: local

networks:
  skillforge-net:
    driver: bridge